//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKSS_BS5_AdminLTE3.AdminLTE3_Component.forms
{


    public partial class validation
    {
    }
}
